net/nfp: replace strncpy by strlcpy
GCC 8.1 error:

drivers/net/nfp/nfp_nspu.c: In function
‘nfp_nspu_set_bar_from_symbl.constprop’:
drivers/net/nfp/nfp_nspu.c:426:2: error: ‘strncpy’ output truncated
before terminating nul copying as many bytes from a string as its length
[-Werror=stringop-truncation]
  strncpy(sym_buf, symbl, strlen(symbl));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: dd63df2bfff3 ("net/nfp: add NSP symbol resolution command")
Cc: alejandro.lucero@netronome.com

Signed-off-by: Yongseok Koh <yskoh@mellanox.com>