net/mlx4: fix possible uninitialized variable
[ upstream commit 554f06d10b1c646f20d7011a30b26fb43507d596 ]

When compiling with gcc -O1, this error appears:
	drivers/net/mlx4/mlx4_ethdev.c: In function ‘mlx4_rxmode_toggle’:
	rte_log.h:321:3: error:
	‘mode’ may be used uninitialized in this function

The function mlx4_rxmode_toggle is never called with a value which
is not in the switch block, but GCC complains about it with -O1.
So the default case is "fixed" by setting string "undefined".

Fixes: eacaac7bae36 ("net/mlx4: restore promisc and allmulti support")

Signed-off-by: Thomas Monjalon <thomas@monjalon.net>