kni: fix kernel 5.4 build - merged pci_aspm.h
Due to kernel change [1] pci-aspm.h no more exists and we need to
include just pci.h instead in kernels >=5.4

The failure due to that is just a not-found include:
/usr/src/dpdk-rte-kni-18.11.2/ethtool/ixgbe/kcompat.h:2225:10:
fatal error: linux/pci-aspm.h: No such file or directory
 2225 | #include <linux/pci-aspm.h>

Fix it by including just pci.h depending on kernel version we build
against.

Not applying to master branch due to kni ethtool being removed in [2]

[1]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7ce2e76a
[2]: https://git.dpdk.org/dpdk/commit/?id=ea6b39b5

Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>
Acked-by: Luca Boccassi <bluca@debian.org>