table: fix casting cuckoo hash function
GCC 8.1 error:

lib/librte_table/rte_table_hash_cuckoo.c: In function
‘rte_table_hash_cuckoo_create’:
lib/librte_table/rte_table_hash_cuckoo.c:139:16: error: cast between
incompatible function types from ‘rte_table_hash_op_hash’ {aka ‘long
unsigned int (*)(void *, void *, unsigned int,  long unsigned int)’} to
‘uint32_t (*)(const void *, uint32_t,  uint32_t)’ {aka ‘unsigned int
(*)(const void *, unsigned int,  unsigned int)’}
[-Werror=cast-function-type]
   .hash_func = (rte_hash_function)(p->f_hash),
                ^

This issue is fixed by [1] in dpdk/master, but this patch is a workaround
to not break API/ABI in stable branch and originally suggested by
Andy Green [2].

[1] commit 8ea41438832a ("table: add dedicated params struct for cuckoo hash")
[2] https://mails.dpdk.org/archives/dev/2018-May/100405.html

Fixes: 5a80bf0ae613 ("table: add cuckoo hash")
Cc: guruprasadx.rao@intel.com

Suggested-by: Andy Green <andy@warmcat.com>
Signed-off-by: Yongseok Koh <yskoh@mellanox.com>